### ISSUE TITLE
The result consistency provision is contradictory

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/EIP-2362#3]
## Description

Current proposal reads:

> `resultFor` MUST revert if the result for an `id` is not available yet. `resultFor` MUST return the same result for an `id` after that result is available.

However, short after, it explains that IDs are deterministically derived from an asset pair descriptor:

> `id`: Description of the required value. Should be standard between all providers. Proposition: use the keccak256 hash of a string describing the requested pair* 

It becomes apparent that both statements are in partial contradiction. If someone implemented business logic that strictly complied with the current language, it would be impossible to update the price point after it is initially set.

## Proposal

It comes to my mind that we have two alternative clear paths to follow from this point:
- Removing the consistency provision (`resultFor MUST return the same result for an `id` after that result is available.`)
- Advancing towards including a time reference inside the query ID so they are still predictably built but they are sensitive to time.

**Comment by themandalore** [comment]
Wouldn't you want to just handle the time sensitivity in the app itself?

**Comment by aesedepece** [comment]
The main problem here is this:

> If someone implemented business logic that strictly complied with the current language, it would be impossible to update the price point after it is initially set.

Consider a consumer contract `C` reading from a price feed contract `F` through an EIP-2362 compliant interface:

- At some point early in time, `C` may query for a price pair identified by the ID while such data is not yet available in `F`. Transaction would revert.

- At a later point in time, contract `C` may again query for the same price pair ID, but this time the data is already available in `F`. Transaction will succeed and the result would be read as expected.

The problem comes now: if at a later point in time, contract `C` queries again for the same price pair ID for which it successfully read the response before, what should happen?

From the current language, one can expect that this third transaction would succeed and that the result must be exactly the same as it got before. But that would be totally defeating the purpose of a price feed: a new query for the same price pair ID should return updated price data for that price pair, not the same data over and over.

**Comment by Amxx** [comment]
I'll be for replacing the consistency provision with a monotony condition. Something like:

`valueFor` MUST either:
- return the same result (same `timestamp` and same ` value`)
or 
- return a more recent result (new `timestamp` strictly greater then the previous one)

**Comment by themandalore** [comment]
I think in Contract C, you would just specify that (timestamp > now - 1 day) or something similar.  The different oracles update at different frequency, How the specific contract would want to weight the various time updates would be up to them.  But if you have a medianizer contract where 1 oracle updates every day, 1 every hour, and 1 every minute...there's still ways to use all 3, but it should be flexible enough to be left up to the contract creator
